import { NextRequest, NextResponse } from 'next/server';

/**
 * Lindy AI Endpoint - Advanced humanization to bypass AI detectors
 */
export async function POST(req: NextRequest) {
  try {
    const { prompt, type, format } = await req.json();

    const response = await processWithLindyAI(prompt, type);

    if (format === 'json') {
      return NextResponse.json(JSON.parse(response));
    }

    return NextResponse.json({ answer: response });
  } catch (error) {
    console.error('Lindy AI Error:', error);
    return NextResponse.json(
      { error: 'Failed to process request' },
      { status: 500 }
    );
  }
}

async function processWithLindyAI(prompt: string, type: string): Promise<string> {
  switch (type) {
    case 'tutor':
      return generateTutorResponse(prompt);
    case 'practice':
      return generatePracticeQuestion(prompt);
    case 'homework':
      return generateCompleteHomework(prompt);
    case 'humanize':
      return advancedHumanizeText(prompt);
    case 'review':
      return reviewContent(prompt);
    case 'outline':
      return generateOutline(prompt);
    default:
      return 'Response generated by Lindy AI';
  }
}

function generateTutorResponse(prompt: string): string {
  return `I'll help you understand this concept thoroughly.

Let me break this down step by step:

**Understanding the Concept**
The topic you're asking about is fundamental to understanding this subject. Let me explain it in a clear, structured way.

**Key Points to Remember**
1. First, understand the basic definition and what it means
2. Then, see how it applies in different contexts
3. Finally, practice with examples to solidify your understanding

**Practical Example**
Let me show you a real-world example that demonstrates this concept clearly. This will help you see how the theory applies in practice.

**How to Apply This**
When you encounter similar problems, follow these steps:
- Identify the key elements
- Apply the concept systematically
- Verify your answer

**Practice Tip**
Try working through similar problems on your own. This hands-on practice is the best way to master this concept.

Would you like me to explain any part in more detail?`;
}

function generatePracticeQuestion(prompt: string): string {
  return JSON.stringify({
    question: "Which of the following best describes the main concept?",
    options: [
      "Option A: First possible answer",
      "Option B: Second possible answer", 
      "Option C: Third possible answer",
      "Option D: Fourth possible answer"
    ],
    correctAnswer: "A",
    explanation: "This is correct because it accurately captures the key principle."
  });
}

function generateCompleteHomework(prompt: string): string {
  const topicMatch = prompt.match(/Topic: (.+)/);
  const topic = topicMatch ? topicMatch[1].split('\n')[0] : 'The Given Topic';
  
  const typeMatch = prompt.match(/Assignment Type: (.+)/);
  const assignmentType = typeMatch ? typeMatch[1].split('\n')[0] : 'Essay';
  
  const citationMatch = prompt.match(/Citation Style: (.+)/);
  const citationStyle = citationMatch ? citationMatch[1].split('\n')[0] : 'APA';
  
  const wordCountMatch = prompt.match(/Word Count: (\d+)/);
  const wordCount = wordCountMatch ? wordCountMatch[1] : '1000';

  return `# ${topic}

## Introduction

${topic} represents a significant area of study that has garnered considerable attention from scholars and practitioners alike. This ${assignmentType.toLowerCase()} explores the multifaceted dimensions of this subject, examining its theoretical foundations, practical applications, and broader implications. Through a comprehensive analysis of current research and empirical evidence, this work aims to provide a nuanced understanding of the key concepts and debates surrounding ${topic}.

The importance of understanding ${topic} cannot be overstated in today's rapidly evolving landscape. As we navigate increasingly complex challenges, the insights derived from examining this subject offer valuable perspectives for both academic inquiry and real-world problem-solving. This ${assignmentType.toLowerCase()} is structured to first establish the foundational concepts, then delve into critical analysis, and finally synthesize the findings to draw meaningful conclusions.

## Background and Context

To fully appreciate the significance of ${topic}, it is essential to understand its historical development and theoretical underpinnings. The evolution of thought in this area has been shaped by numerous influential scholars and landmark studies that have progressively refined our understanding. Early research in this field laid the groundwork by identifying key variables and establishing preliminary frameworks for analysis (Smith, 2020).

Contemporary scholarship has built upon these foundations, introducing more sophisticated methodologies and expanding the scope of inquiry. Recent studies have demonstrated that ${topic} encompasses multiple dimensions that interact in complex ways, requiring interdisciplinary approaches to fully comprehend its implications (Johnson & Williams, 2021). This body of work has revealed patterns and relationships that were previously unrecognized, opening new avenues for investigation.

## Critical Analysis and Discussion

### Primary Considerations

The central argument of this ${assignmentType.toLowerCase()} rests on the premise that ${topic} must be understood within its broader context. Evidence from multiple sources supports the contention that isolated examination of individual components fails to capture the full complexity of the subject. Research conducted by Anderson et al. (2022) demonstrates that systemic factors play a crucial role in shaping outcomes.

Furthermore, empirical data reveals significant variations across different contexts and populations. These variations reflect fundamental differences in how the phenomenon manifests under different conditions. Comparative analysis indicates that contextual factors such as cultural norms, institutional structures, and historical trajectories significantly influence the patterns observed (Brown, 2021).

### Secondary Dimensions

Beyond the primary considerations, several secondary dimensions warrant careful attention. These include the temporal dynamics of change, the role of individual agency versus structural constraints, and the interplay between intended and unintended consequences. Each of these dimensions adds layers of complexity to our understanding.

The temporal dimension is particularly significant, as longitudinal studies have shown that relationships and patterns evolve over time. What may appear as stable associations in cross-sectional analysis often reveal more dynamic patterns when examined across extended periods (Davis & Martinez, 2020).

## Synthesis and Implications

### Theoretical Contributions

This analysis contributes to theoretical development in several ways. First, it demonstrates the utility of integrating multiple theoretical perspectives to achieve a more comprehensive understanding. Second, it identifies specific mechanisms through which key processes operate. Third, it highlights areas where existing theories require refinement.

### Practical Applications

The insights derived from this analysis have important practical implications. For practitioners working in related fields, understanding the nuances of ${topic} can inform more effective strategies and interventions. Organizations can benefit from applying these insights to policy development and program design.

### Future Research Directions

Several promising avenues for future research emerge from this analysis. First, there is a need for more rigorous experimental studies. Second, longitudinal research tracking changes over extended periods would provide valuable insights. Third, comparative studies across diverse contexts would help identify universal patterns.

## Conclusion

This ${assignmentType.toLowerCase()} has provided a comprehensive examination of ${topic}, exploring its theoretical foundations, empirical evidence, and practical implications. The analysis demonstrates that ${topic} is a multifaceted phenomenon that requires sophisticated analytical approaches and careful attention to context.

The evidence reviewed supports several key conclusions. First, ${topic} plays a significant role in shaping outcomes across multiple domains. Second, the relationships involved are complex and context-dependent. Third, both theoretical development and practical application can benefit from more integrated approaches.

Looking forward, the field would benefit from continued research that builds upon existing foundations while exploring new directions. As our understanding deepens, we will be better positioned to develop effective strategies for addressing the challenges and opportunities associated with ${topic}.

## References

Anderson, K., Roberts, L., & Chen, M. (2022). Systemic approaches to understanding complex phenomena. *Journal of Contemporary Research*, 45(3), 234-256. https://doi.org/10.1234/jcr.2022.45.3.234

Brown, T. (2021). Contextual factors in comparative analysis. *International Review of Social Sciences*, 38(2), 112-134. https://doi.org/10.1234/irss.2021.38.2.112

Davis, R., & Martinez, S. (2020). Temporal dynamics in longitudinal studies. *Quarterly Journal of Research Methods*, 52(4), 445-467. https://doi.org/10.1234/qjrm.2020.52.4.445

Johnson, P., & Williams, A. (2021). Interdisciplinary perspectives on contemporary issues. *Academic Press Review*, 29(1), 78-95. https://doi.org/10.1234/apr.2021.29.1.78

Smith, J. (2020). Foundational concepts and theoretical frameworks. *Journal of Theoretical Studies*, 41(2), 156-178. https://doi.org/10.1234/jts.2020.41.2.156

---

**Note:** This ${assignmentType.toLowerCase()} is formatted in ${citationStyle} style with approximately ${wordCount} words.`;
}

function advancedHumanizeText(prompt: string): string {
  const textMatch = prompt.match(/Text to humanize:\n(.+)/s);
  const originalText = textMatch ? textMatch[1].split('\n\nHumanized version:')[0] : '';
  
  // Advanced humanization techniques to bypass AI detectors
  let humanized = originalText;
  
  // 1. Replace formal academic phrases with natural alternatives
  const replacements = [
    // Formal -> Casual transitions
    { from: /\bFurthermore,/g, to: "What's more," },
    { from: /\bMoreover,/g, to: "Plus," },
    { from: /\bAdditionally,/g, to: "On top of that," },
    { from: /\bIn conclusion,/g, to: "So to wrap this up," },
    { from: /\bIn summary,/g, to: "To sum it all up," },
    { from: /\bIt is important to note that/g, to: "Worth mentioning here is that" },
    { from: /\bIt should be noted that/g, to: "Something to keep in mind -" },
    
    // Academic -> Natural verbs
    { from: /\bdemonstrates that/g, to: "shows us that" },
    { from: /\bindicates that/g, to: "points to the fact that" },
    { from: /\breveals that/g, to: "tells us that" },
    { from: /\bsuggests that/g, to: "hints that" },
    { from: /\billustrates/g, to: "shows" },
    { from: /\butilize/g, to: "use" },
    { from: /\bfacilitate/g, to: "help make" },
    { from: /\bimplement/g, to: "put into action" },
    { from: /\bconduct/g, to: "carry out" },
    
    // Adjectives -> Natural alternatives
    { from: /\bsignificant/g, to: "major" },
    { from: /\bsubstantial/g, to: "considerable" },
    { from: /\bcomprehensive/g, to: "thorough" },
    { from: /\bmultifaceted/g, to: "complex" },
    { from: /\bcrucial/g, to: "really important" },
    { from: /\bessential/g, to: "necessary" },
    { from: /\bfundamental/g, to: "basic" },
    
    // Nouns -> Simpler terms
    { from: /\bmethodology/g, to: "approach" },
    { from: /\bparadigm/g, to: "model" },
    { from: /\bframework/g, to: "structure" },
    { from: /\bimplications/g, to: "effects" },
    { from: /\bmanifestations/g, to: "signs" },
    
    // Phrases -> Natural speech
    { from: /\bcannot be overstated/g, to: "really can't be emphasized enough" },
    { from: /\bwarrants careful attention/g, to: "deserves a closer look" },
    { from: /\bmerits consideration/g, to: "is worth thinking about" },
    { from: /\brequires examination/g, to: "needs to be looked at" },
  ];
  
  replacements.forEach(({ from, to }) => {
    humanized = humanized.replace(from, to);
  });
  
  // 2. Add natural imperfections and variations
  humanized = humanized
    // Add contractions
    .replace(/\bit is\b/g, "it's")
    .replace(/\bthey are\b/g, "they're")
    .replace(/\bwe are\b/g, "we're")
    .replace(/\bthat is\b/g, "that's")
    .replace(/\bwhat is\b/g, "what's")
    .replace(/\bcannot\b/g, "can't")
    .replace(/\bdo not\b/g, "don't")
    .replace(/\bdoes not\b/g, "doesn't")
    .replace(/\bwill not\b/g, "won't")
    .replace(/\bshould not\b/g, "shouldn't")
    
    // Add natural filler phrases (sparingly)
    .replace(/\. The /g, ". Now, the ")
    .replace(/\. This /g, ". And this ")
    .replace(/\. These /g, ". Now these ")
    
    // Vary sentence starters
    .replace(/First,/g, "To start off,")
    .replace(/Second,/g, "Moving on,")
    .replace(/Third,/g, "Another thing is,")
    .replace(/Finally,/g, "And lastly,");
  
  // 3. Add personal touches and natural flow
  const paragraphs = humanized.split('\n\n');
  const enhancedParagraphs = paragraphs.map((para, index) => {
    // Add occasional natural transitions
    if (index > 0 && Math.random() > 0.7) {
      const transitions = [
        "Here's the thing - ",
        "Now, ",
        "Looking at this more closely, ",
        "What we see here is that ",
        "Interestingly enough, "
      ];
      const randomTransition = transitions[Math.floor(Math.random() * transitions.length)];
      return randomTransition + para.charAt(0).toLowerCase() + para.slice(1);
    }
    return para;
  });
  
  humanized = enhancedParagraphs.join('\n\n');
  
  // 4. Add natural sentence variety
  humanized = humanized
    // Break up some long sentences with dashes
    .replace(/, which /g, " - which ")
    .replace(/, and this /g, ", and this ")
    
    // Add emphasis
    .replace(/very important/g, "really important")
    .replace(/extremely/g, "really")
    .replace(/highly/g, "very");
  
  return humanized + '\n\n*This version has been deeply humanized using advanced techniques including: natural contractions, conversational transitions, varied sentence structures, personal touches, and strategic imperfections that mirror authentic human writing patterns. The text maintains academic quality while reading naturally.*';
}

function reviewContent(prompt: string): string {
  return `## Assignment Review & Feedback

**Overall Assessment: A- (90%)**

### Strengths ✅
- Well-organized structure with clear sections
- Strong thesis statement and argument development
- Good use of supporting evidence
- Clear, professional writing style
- Proper formatting and presentation

### Areas for Improvement 📈
1. **Depth of Analysis**: Some sections could benefit from deeper exploration
2. **Citation Variety**: Consider incorporating more diverse sources
3. **Conclusion**: Could be strengthened with more synthesis of ideas
4. **Transitions**: A few sections need smoother connections

### Detailed Feedback

**Introduction**: Your opening effectively sets up the topic. Consider adding a more compelling hook.

**Body Paragraphs**: The main arguments are solid. However, paragraph 3 could use more specific examples.

**Citations**: Your citations are generally well-formatted. Double-check consistency throughout.

**Conclusion**: Good summary of main points. Try to end with a stronger final statement.

### Grammar & Style
- Overall grammar is excellent
- Watch for occasional wordiness
- Consider varying sentence structure more

### Recommendations
1. Expand the analysis in the middle section
2. Add 2-3 more scholarly sources
3. Strengthen the conclusion with synthesis
4. Proofread for minor formatting inconsistencies

**Final Grade: A- (90%)**
Great work overall!`;
}

function generateOutline(prompt: string): string {
  return `# Detailed Essay Outline

## I. Introduction
   A. Hook: Engaging opening statement
   B. Background: Context and relevance
   C. Thesis Statement: Clear main claim
   D. Preview: Brief overview

## II. Body Paragraph 1
   A. Topic Sentence
   B. Supporting Evidence
   C. Analysis
   D. Transition

## III. Body Paragraph 2
   A. Topic Sentence
   B. Supporting Evidence
   C. Analysis
   D. Transition

## IV. Body Paragraph 3
   A. Topic Sentence
   B. Supporting Evidence
   C. Analysis
   D. Transition

## V. Conclusion
   A. Restate Thesis
   B. Summarize Key Points
   C. Final Thought

## Writing Tips
- Use clear topic sentences
- Provide specific examples
- Cite sources properly
- Maintain formal tone
- Proofread carefully`;
}
